# Generated by Django 5.2.6 on 2025-09-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(default="No description yet"),
            preserve_default=False,
        ),
    ]
