# Generated by Django 5.2.6 on 2025-09-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_product_category_remove_product_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(default="No description available"),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(default="No description available"),
        ),
    ]
